Make monkey patched `get_user_model()` more robust.
Using the `override_settings` decorator was occasionally causing this error for
media requests, triggered by middleware that checks authentication:

Traceback:
File "path/to/site-packages/django/core/handlers/base.py" in get_response
  87.                 response = middleware_method(request)
File "path/to/site-packages/publisher/middleware.py" in process_request
  14.         PublisherMiddleware._draft_status[current_thread()] = self.is_draft(request)
File "path/to/myproject/middleware.py" in is_draft
  8.         if request.user.is_authenticated() and \
File "path/to/site-packages/django/utils/functional.py" in inner
  224.             self._setup()
File "path/to/site-packages/django/utils/functional.py" in _setup
  357.         self._wrapped = self._setupfunc()
File "path/to/site-packages/django/contrib/auth/middleware.py" in <lambda>
  22.         request.user = SimpleLazyObject(lambda: get_user(request))
File "path/to/site-packages/django/contrib/auth/middleware.py" in get_user
  10.         request._cached_user = auth.get_user(request)
File "path/to/site-packages/django/contrib/auth/__init__.py" in get_user
  159.             user = backend.get_user(user_id)
File "path/to/site-packages/django/contrib/auth/backends.py" in get_user
  67.         UserModel = get_user_model()
File "path/to/site-packages/django/test/utils.py" in inner
  216.                     return test_func(*args, **kwargs)
File "path/to/site-packages/django/test/utils.py" in __exit__
  201.         self.disable()
File "path/to/site-packages/django/test/utils.py" in disable
  248.         settings._wrapped = self.wrapped

Exception Type: AttributeError at /media/...jpg
Exception Value: 'override_settings' object has no attribute 'wrapped'